name: auto_tag
on:
  workflow_run:
    workflows: main
    branches:
      - master
      - feature/async
    types: completed
jobs:
  verify-build-successful:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - name: ❌ Fail if calling workflow has failed
        run: exit 1
  create-release-tag:
    runs-on: ubuntu-22.04
    needs: verify-build-successful
    steps:
      - name: ✅ Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 📍 Create and push new tag
        run: ./build.sh CreateReleaseTag
        env:
          GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write
