on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ./build.sh compile
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ./build.sh unit-test
