on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository preserving full history (needed for GitVersion)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run nuke (compile)
        run: ./build.sh compile
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository preserving full history (needed for GitVersion)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run nuke (unit-test)
        run: ./build.sh unit-test
      - name: Upload test results report
        uses: actions/upload-artifact@v4
        with:
          path: test/Dvchevskii.Optional.Tests/TestResults/testResults.html
          name: testResults.html
