on:
  push:
    branches: [master, feature/*]
jobs:
  pack:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./build.sh output-version-env
      - run: ./build.sh pack --configuration Release
      - uses: actions/upload-artifact@v4
        with:
          path: src/Dvchevskii.Optional/bin/Release/Dvchevskii.Optional.*.{nupkg,snupkg}
          name: "Dvchevskii.Optional_v${{ env.GITVERSION_SEMVER }}"
