on:
  push:
    tags: v*.*
jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: ✅ Repository checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
  build-artifacts:
    runs-on: ubuntu-22.04
    needs: [unit-test]
    steps:
      - name: ✅ Repository checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Set environment variable with calculated semantic version
        run: ./build.sh actions-set-semver
      - name: 🔨 Compile (Release)
        run: ./build.sh compile-main --configuration Release
      - name: 📦 Create packages
        run: ./build.sh pack --configuration Release
      - name: 💾 Upload packages to artifact storage
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            src/Dvchevskii.Optional/bin/Release/Dvchevskii.Optional.${{ env.GITVERSION_SEMVER }}.nupkg
            src/Dvchevskii.Optional/bin/Release/Dvchevskii.Optional.${{ env.GITVERSION_SEMVER }}.snupkg
      - name: 💾 Upload libraries to artifact storage
        uses: actions/upload-artifact@v4
        with:
          name: netstandard2.0
          path: src/Dvchevskii.Optional/bin/Release/netstandard2.0/*

  draft-release:
    runs-on: ubuntu-22.04
    needs: [unit-test, build-artifacts]
    steps:
      - name: ✅ Repository checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Download built artifacts 1/2
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: artifacts/packages
      - name: Download built artifacts 2/2
        uses: actions/download-artifact@v4
        with:
          name: netstandard2.0
          path: artifacts/libraries
      - name: Create release draft
        run: ./build.sh create-release-draft
    permissions:
      contents: write
