on:
  push:
    branches: master

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: ✅ Repository checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: 🧪 Run unit tests
        run: ./build.sh unit-test --configuration Debug
  push-tag:
    runs-on: ubuntu-22.04
    needs: unit-test
    steps:
      - name: ✅ Repository checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: 🚩 Create tag with calculated next version
        run: ./build.sh create-version-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
