on:
  release:
    types: [published]

jobs:
  push-artifacts:
    runs-on: ubuntu-22.04
    steps:
      - name: ✅ Repository checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Download release artifacts
        run: ./build.sh download-release-artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🚚 Run push artifacts target
        run: ./build.sh nuget-push-artifacts
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
